<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Spatie\MediaLibrary\HasMedia; // for spatie Media
use Spatie\MediaLibrary\InteractsWithMedia; // for spatie Media
use Spatie\MediaLibrary\MediaCollections\Models\Media;

use RalphJSmit\Laravel\SEO\Support\HasSEO;
use RalphJSmit\Laravel\SEO\Support\SEOData;


class Category extends Model implements HasMedia
{
    use InteractsWithMedia, HasSEO;
    protected $guarded = [];

    protected $with = ['media'];

    public function registerMediaConversions(Media $media = null): void
    {
        // Convert all images to webp format for better performance
        $this->addMediaConversion('webp')
            ->format('webp')
            ->nonQueued(); // Use nonQueued for smaller apps, or queued for larger ones

        // Create a thumbnail version (optional but very useful!)
        $this->addMediaConversion('thumb')
            ->format('webp') // Also make the thumbnail webp
            ->width(300)
            ->height(200)
            ->sharpen(10) // Make it a bit sharper
            ->nonQueued();
    }

    // seo
    public function getDynamicSEOData(): SEOData
    {
        return new SEOData(
            title: $this->seo->title ?? $this->title,
            description: $this->seo->description,
            image: $this->seo->image
        );
    }

    // handle seo delete request
    protected static function booted(): void
    {
        // This 'deleting' event fires right before a Category is deleted.
        static::deleting(function (Category $category) {
            // Check if SEO data exists before trying to delete it.
            if ($category->seo) {
                $category->seo->delete();
            }
        });
    }

    public function events()
    {
        return $this->belongsToMany(Event::class);
    }

    public function image()
    {
        $media = $this->getFirstMediaUrl('image', 'webp');

        return $media
            ? $media  // full URL generated by Spatie
            : asset('no-image.webp');  // fallback
    }


}
