<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Spatie\MediaLibrary\HasMedia; // for spatie Media
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

use RalphJSmit\Laravel\SEO\Support\HasSEO;
use RalphJSmit\Laravel\SEO\Support\SEOData;

class Event extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasSEO;

    protected $guarded = [];

    // this will auto load realation with eager load
    protected $with = ['media'];

    public function registerMediaConversions(Media $media = null): void
    {
        // Convert all images to webp format for better performance
        $this->addMediaConversion('webp')
            ->format('webp')
            ->nonQueued();

        // Create a thumbnail version (optional but very useful!)
        $this->addMediaConversion('thumb')
            ->format('webp')
            ->width(426)
            ->height(240)
            ->sharpen(10)
            ->nonQueued();
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('organizer_image')
            ->singleFile();
    }

    // seo
    public function getDynamicSEOData(): SEOData
    {
        return new SEOData(
            title: $this->seo->title ?? $this->title,
            description: $this->seo->description,
            image: $this->seo->image
        );
    }

    // handle seo delete request
    protected static function booted(): void
    {
        // This 'deleting' event fires right before an items is deleted.
        static::forceDeleted(function (Event $event) {
            // Check if SEO data exists before trying to delete it.
            if ($event->seo) {
                $event->seo->delete();
            }
        });
    }


    protected $casts =
        [
            'start_datetime' => 'datetime',
            'end_datetime' => 'datetime',
            'published' => 'boolean',
            'featured' => 'boolean',
            'other' => 'array'
        ];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function ticketTypes()
    {
        return $this->hasMany(TicketType::class);
    }

    public function addOns()
    {
        return $this->hasMany(AddOn::class);
    }

    public function taxRate()
    {
        return $this->belongsTo(TaxRate::class);
    }

    public function getTotalAttendeesAttribute(): int
    {
        return \App\Models\Ticket::whereHas('ticketType', function ($query) {
            $query->where('event_id', $this->id);
        })
            ->whereHas('order', function ($query) {
                $query->whereIn('status', ['pending', 'completed']);
            })
            ->count();
    }

    public function getFormattedAttendeesAttribute(): string
    {
        $count = $this->total_attendees;
        if ($count >= 1000) {
            return round($count / 1000, 1) . 'K';
        }
        return (string) $count;
    }

    public function getMapCoordsAttribute(): ?array
    {
        if (!$this->map_link)
            return null;

        $cacheKey = 'event_map_coords_' . $this->id;

        return cache()->rememberForever($cacheKey, function () {
            // Try direct regex match for full Google Maps URLs
            if (preg_match('/@(-?\d+\.\d+),(-?\d+\.\d+)/', $this->map_link, $m)) {
                return ['lat' => $m[1], 'lng' => $m[2]];
            }

            // Try to resolve short URLs (goo.gl) by following redirect
            try {
                $ch = curl_init($this->map_link);
                curl_setopt($ch, CURLOPT_HEADER, false);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
                curl_setopt($ch, CURLOPT_MAXREDIRS, 3);
                                curl_setopt($ch, CURLOPT_TIMEOUT, 2);
                curl_exec($ch);
                $finalUrl = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
                curl_close($ch);

                if ($finalUrl && $finalUrl !== $this->map_link && preg_match('/@(-?\d+\.\d+),(-?\d+\.\d+)/', $finalUrl, $m)) {
                    return ['lat' => $m[1], 'lng' => $m[2]];
                }
            } catch (\Exception $e) {
                // Silently fail
            }

            return null;
        });
    }


    public function image()
    {
        $media = $this->getFirstMediaUrl('image', 'webp');

        return $media
            ? $media  // full URL generated by Spatie
            : asset('no-image.webp');  // fallback
    }
}
